### ISSUE TITLE
Ask for processed datasets

### ISSUE THREAD

**Issue by ZhongAobo** [emadeldeen24/TSLANet#1]
Hello, I am very interested in your research project. Can you provide some processed datasets for reference. I want to conduct experiments on other datasets, but I am not sure about the format of datasets in this project.

**Comment by emadeldeen24** [comment]
The preprocessing of the classification datasets is quite similar to the ones in our [TS-TCC](https://github.com/emadeldeen24/TS-TCC) work. You can check.
