### ISSUE TITLE
question about datasets in Classification task

### ISSUE THREAD

**Issue by c0syfeng** [emadeldeen24/TSLANet#2]
hi，your work is very gorgeous.I am reproducing ur work,which  be interested. Could you share your UCR dataset?
UCRdataset i got don't incould trian.pt,val.pt,test.pt.Thank you!
looking forward to your reply.

**Comment by emadeldeen24** [comment]
The data is already public and preprocessing codes are the same as my previous works, eg., https://github.com/emadeldeen24/TS-TCC/tree/main/data_preprocessing/epilepsy
