### ISSUE TITLE
Request for Access to Anomaly Detection Code

### ISSUE THREAD

**Issue by permanent322** [emadeldeen24/TSLANet#3]
Your work has been incredibly insightful, and I believe it could greatly assist my current research.
I am particularly interested in the anomaly detection component of your project. I have reviewed the documentation and code available in the repository, but I am unable to locate the specific code pertaining to anomaly detection. It would be immensely helpful for my studies if I could access this part of the code. Would it be possible for you to provide me with the anomaly detection code or guide me on how to access it?

**Comment by emadeldeen24** [comment]
For anomaly detection experiments, we used the same code in https://github.com/DAMO-DI-ML/NeurIPS2023-One-Fits-All/tree/main/Anomaly_Detection  but replaced the model with ours.
