### ISSUE TITLE
about ASB model

### ISSUE THREAD

**Issue by Tong-Hao741** [emadeldeen24/TSLANet#4]
hi is a amazing work,I have a small problem with the ASB model. Upon checking the code, I found that values greater than θ were retained instead of being filtered out. Is it because I misunderstood the concept of high frequency? Please kindly answer your questions : )

**Comment by zhshLii** [comment]
I think you may misunderstand the meaning of values. The value represents energy (like Amplitude) instead of frequency. The freq with energy greater than θ is important that need to be retained.

**Comment by Tong-Hao741** [comment]
It turns out that energy greater than θ does not necessarily correspond to high frequencies, but rather adaptively trains a threshold. However, I still haven't figured out how to filter or attenuate high frequencies from the code? Could you please provide a brief explanation? Thank you very much~

**Comment by zhshLii** [comment]
It's a good question. But I cannot answer this. I also want to know how to update the trainable threshold, since the torch.quantile is not differentiable #5. Do you have any idea?

**Comment by emadeldeen24** [comment]
fixed

**Comment by Tong-Hao741** [comment]
For the differential strategy of discrete data, Gumbel Softmax can be referred to, which is widely used in many places
