### ISSUE TITLE
The parameters for the weather？

### ISSUE THREAD

**Issue by 137824** [emadeldeen24/TSLANet#6]
How were the parameters for the weather dataset set? I cannot replicate the results following the .sh file.
1. ps=8 your paper in arxiv v1
2. ps=64 your .sh file
![图片](https://github.com/emadeldeen24/TSLANet/assets/23304395/cf67061f-61a9-4ae8-8239-0c18b4542349)
![图片](https://github.com/emadeldeen24/TSLANet/assets/23304395/a3c2d612-fa39-46c4-a0ad-e10356583ec0)

**Comment by huangst21** [comment]
> How were the parameters for the weather dataset set? I cannot replicate the results following the .sh file.
> 
> 1. ps=8 your paper in arxiv v1
> 2. ps=64 your .sh file
>    ![图片](https://private-user-images.githubusercontent.com/23304395/344733820-cf67061f-61a9-4ae8-8239-0c18b4542349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM4MjAtY2Y2NzA2MWYtNjFhOS00YWU4LTgyMzktMGMxOGI0NTQyMzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YjM3NjFlYjNiZDYyZWZiMWEzZGJjNmNmYWI0ZTRlM2JkNTg5MThhNmI3ZjFmNmYzOWQ3YTNiYTA0MzdiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Xu5zNFrleGlve_JWktheGMGhceHkZC5cyaQIXfmQe8)
>    ![图片](https://private-user-images.githubusercontent.com/23304395/344733939-a3c2d612-fa39-46c4-a0ad-e10356583ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM5MzktYTNjMmQ2MTItZmEzOS00NmM0LWEwYWQtZTEwMzU2NTgzZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTI3YjJhYzEwYWUyY2RhOWQ4MDZjMGU4YjkxMjU1YTk2Y2M5NzNhYmUxZGQ5NmE3MmMwMWUxZmY0NWE5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WA4K17yiNRiWuhToEQULjOI2jxEonD8C-ZKk4ynJSu0)

I get similar results to yours and I'm confused ....

**Comment by 137824** [comment]
> > How were the parameters for the weather dataset set? I cannot replicate the results following the .sh file.
> > 
> > 1. ps=8 your paper in arxiv v1
> > 2. ps=64 your .sh file
> >    ![图片](https://private-user-images.githubusercontent.com/23304395/344733820-cf67061f-61a9-4ae8-8239-0c18b4542349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM4MjAtY2Y2NzA2MWYtNjFhOS00YWU4LTgyMzktMGMxOGI0NTQyMzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YjM3NjFlYjNiZDYyZWZiMWEzZGJjNmNmYWI0ZTRlM2JkNTg5MThhNmI3ZjFmNmYzOWQ3YTNiYTA0MzdiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Xu5zNFrleGlve_JWktheGMGhceHkZC5cyaQIXfmQe8)
> >    ![图片](https://private-user-images.githubusercontent.com/23304395/344733939-a3c2d612-fa39-46c4-a0ad-e10356583ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM5MzktYTNjMmQ2MTItZmEzOS00NmM0LWEwYWQtZTEwMzU2NTgzZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTI3YjJhYzEwYWUyY2RhOWQ4MDZjMGU4YjkxMjU1YTk2Y2M5NzNhYmUxZGQ5NmE3MmMwMWUxZmY0NWE5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WA4K17yiNRiWuhToEQULjOI2jxEonD8C-ZKk4ynJSu0)
> 
> I get similar results to yours and I'm confused ....

--seq_len 336

**Comment by huangst21** [comment]
> > > How were the parameters for the weather dataset set? I cannot replicate the results following the .sh file.
> > > 
> > > 1. ps=8 your paper in arxiv v1
> > > 2. ps=64 your .sh file
> > >    ![图片](https://private-user-images.githubusercontent.com/23304395/344733820-cf67061f-61a9-4ae8-8239-0c18b4542349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM4MjAtY2Y2NzA2MWYtNjFhOS00YWU4LTgyMzktMGMxOGI0NTQyMzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YjM3NjFlYjNiZDYyZWZiMWEzZGJjNmNmYWI0ZTRlM2JkNTg5MThhNmI3ZjFmNmYzOWQ3YTNiYTA0MzdiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Xu5zNFrleGlve_JWktheGMGhceHkZC5cyaQIXfmQe8)
> > >    ![图片](https://private-user-images.githubusercontent.com/23304395/344733939-a3c2d612-fa39-46c4-a0ad-e10356583ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM5MzktYTNjMmQ2MTItZmEzOS00NmM0LWEwYWQtZTEwMzU2NTgzZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTI3YjJhYzEwYWUyY2RhOWQ4MDZjMGU4YjkxMjU1YTk2Y2M5NzNhYmUxZGQ5NmE3MmMwMWUxZmY0NWE5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WA4K17yiNRiWuhToEQULjOI2jxEonD8C-ZKk4ynJSu0)
> > 
> > 
> > I get similar results to yours and I'm confused ....
> 
> --seq_len 336

Did you get the right result after adjusting the seq_len to 336?

**Comment by 137824** [comment]
> > > > How were the parameters for the weather dataset set? I cannot replicate the results following the .sh file.
> > > > 
> > > > 1. ps=8 your paper in arxiv v1
> > > > 2. ps=64 your .sh file
> > > >    ![图片](https://private-user-images.githubusercontent.com/23304395/344733820-cf67061f-61a9-4ae8-8239-0c18b4542349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM4MjAtY2Y2NzA2MWYtNjFhOS00YWU4LTgyMzktMGMxOGI0NTQyMzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YjM3NjFlYjNiZDYyZWZiMWEzZGJjNmNmYWI0ZTRlM2JkNTg5MThhNmI3ZjFmNmYzOWQ3YTNiYTA0MzdiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Xu5zNFrleGlve_JWktheGMGhceHkZC5cyaQIXfmQe8)
> > > >    ![图片](https://private-user-images.githubusercontent.com/23304395/344733939-a3c2d612-fa39-46c4-a0ad-e10356583ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU0MDMsIm5iZiI6MTcyMjA5NTEwMywicGF0aCI6Ii8yMzMwNDM5NS8zNDQ3MzM5MzktYTNjMmQ2MTItZmEzOS00NmM0LWEwYWQtZTEwMzU2NTgzZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTI3YjJhYzEwYWUyY2RhOWQ4MDZjMGU4YjkxMjU1YTk2Y2M5NzNhYmUxZGQ5NmE3MmMwMWUxZmY0NWE5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WA4K17yiNRiWuhToEQULjOI2jxEonD8C-ZKk4ynJSu0)
> > > 
> > > 
> > > I get similar results to yours and I'm confused ....
> > 
> > 
> > --seq_len 336
> 
> Did you get the right result after adjusting the seq_len to 336?

yeap
